# Generated by Django 5.2 on 2025-04-18 08:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Транспорт', 'Транспорт'), ('Недвижимость', 'Недвижимость'), ('Работа', 'Работа'), ('Услуги', 'Услуги'), ('Личные вещи', 'Личные вещи'), ('Для дома и дачи', 'Для дома и дачи'), ('Электроника', 'Электроника'), ('Хобби и отдых', 'Хобби и отдых')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
